### ISSUE TITLE
请问它的检测原理是什么？

### ISSUE THREAD

**Issue by ztm0929** [KoriIku/chatgpt-degrade-checker#3]
本人比较编程小白，看不懂代码，请教下大佬这个检测原理是什么？

我用ChatGPT/PoW/Proof of Work也没能搜到些相关的资料👀

**Comment by KoriIku** [comment]
ChatGPT 会对它认为风险较高的 ip (也包括其它因素) 给出更难的 PoW，因此我们只需要捕捉 PoW 难度，就可以反向推测 ChatGPT 对当前环境的风险评级。

**Comment by ztm0929** [comment]
> ChatGPT 会对它认为风险较高的 ip (也包括其它因素) 给出更难的 PoW，因此我们只需要捕捉 PoW 难度，就可以反向推测 ChatGPT 对当前环境的风险评级。

感谢解答👍👍

**Comment by yzy-lex** [comment]
请问Claude可不可能实现这个效果(✧∀✧)
